USE DONPEPE;

/*VISTA 1*/

CREATE VIEW PRODUCTOS_DISPONIBLES AS
SELECT PRODUCTO.ID, PRODUCTO.NOMBRE, PRODUCTO.MARCA, PRODUCTO.ORIGEN,
PRODUCTO.VOLUMEN, PRODUCTO.PRECIO, PRODUCTO.PESO, PRODUCTO.FOTO, CATEGORIA.NOMBRE AS CATEGORIA
FROM PRODUCTO
INNER JOIN CATEGORIA ON PRODUCTO.ID_CATEGORIA = CATEGORIA.ID;

SELECT*FROM PRODUCTOS_DISPONIBLES;

/*VISTA 2*/

CREATE VIEW CATEGORIAS AS
SELECT CATEGORIA.NOMBRE, CATEGORIA.CONDICIONES_ALMACENAMIENTO, CATEGORIA.OBSERVACIONES
FROM CATEGORIA;

SELECT*FROM CATEGORIAS;


/*VISTA 3*/

CREATE VIEW DOMICILIARIO_ZONAS_REPARTO AS
SELECT DOMICILIARIO.NOMBRE, ZONA.NOMBRE AS ZONAS
FROM DOMICILIARIO
INNER JOIN ZONA ON DOMICILIARIO.CODIGO_POSTAL = ZONA.CODIGO_POSTAL;

SELECT*FROM DOMICILIARIO_ZONAS_REPARTO;


/*VISTA 4*/

CREATE VIEW PEDIDOS AS
SELECT PEDIDO.ID, PEDIDO.FECHA_PEDIDO, CLIENTE.NOMBRE AS CLIENTE, CLIENTE.DIRECCION,
DETALLE_PEDIDO.PRODUCTOS_PEDIDO, PEDIDO.IMPORTE_TOTAL_PEDIDO
FROM CLIENTE
JOIN PEDIDO ON PEDIDO.ID_CLIENTE = CLIENTE.ID
JOIN DETALLE_PEDIDO ON DETALLE_PEDIDO.ID_PEDIDO = PEDIDO.ID;

SELECT*FROM PEDIDOS;






